import { doc, serverTimestamp, setDoc } from 'firebase/firestore'
import { FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { SEO } from '../components/SEO'
import { categories } from '../data/categories'
import { useAuth } from '../context/AuthContext'
import { db } from '../lib/firebase'

export default function BecomeProviderPage() {
  const { user, configured } = useAuth(); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!configured || !db) { setError('Configure Firebase before sending provider applications.'); return } if (!user) { setError('Sign in first so the application can be linked to your account.'); return } const data = new FormData(event.currentTarget); setSaving(true); try { await setDoc(doc(db, 'providerApplications', user.uid), { userId: user.uid, name: String(data.get('name')), phone: String(data.get('phone')), categorySlug: String(data.get('category')), location: String(data.get('location')), experience: String(data.get('experience')), bio: String(data.get('bio')), status: 'pending', submittedAt: serverTimestamp() }, { merge: true }); setMessage('Application saved. You can update it while it is under review.') } catch (e) { setError(e instanceof Error ? e.message : 'Could not save the application.') } finally { setSaving(false) } }
  return <div className="page-shell"><SEO title="Become a provider | WorkShake" description="Join WorkShake as a local service provider and connect with customers who need your skills." path="/become-a-provider" /><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-olive">Work on WorkShake</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-5xl">Turn practical skills into local work.</h1><p className="mt-4 text-lg leading-8 text-forest/80">Create a clear provider profile so customers can understand what you do before they message you.</p><div className="mt-7 rounded-[2rem] bg-sun p-6"><h2 className="font-black">Before applying</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-forest/85"><li>Use accurate service and experience information.</li><li>Only accept jobs you can complete safely and legally.</li><li>Keep quotes clear and confirm scope before starting.</li><li>Build trust through communication and reviews.</li></ul></div></div><form onSubmit={submit} className="grid gap-5 rounded-[2rem] border border-forest/10 bg-mist p-6 shadow-soft"><div className="grid gap-5 sm:grid-cols-2"><label className="form-field"><span className="form-label">Name or business name</span><input required name="name" defaultValue={user?.displayName ?? ''} className="form-input" /></label><label className="form-field"><span className="form-label">Phone</span><input required name="phone" className="form-input" inputMode="tel" /></label></div><div className="grid gap-5 sm:grid-cols-2"><label className="form-field"><span className="form-label">Primary category</span><select required name="category" className="form-select"><option value="">Select</option>{categories.map((c) => <option value={c.slug} key={c.slug}>{c.name}</option>)}</select></label><label className="form-field"><span className="form-label">Service area</span><input required name="location" className="form-input" placeholder="Town / areas covered" /></label></div><label className="form-field"><span className="form-label">Experience</span><input required name="experience" className="form-input" placeholder="e.g. 5 years / certified electrician" /></label><label className="form-field"><span className="form-label">Short provider bio</span><textarea required minLength={30} maxLength={800} name="bio" className="form-textarea" /></label>{!user && <p className="rounded-xl bg-sage p-3 text-sm">Already ready to apply? <Link className="font-black" to="/sign-in">Sign in first.</Link></p>}{error && <p role="alert" className="rounded-xl bg-sun p-3 text-sm font-bold">{error}</p>}{message && <p role="status" className="rounded-xl bg-sage p-3 text-sm font-bold">{message}</p>}<button className="btn-primary w-fit" disabled={saving}>{saving ? 'Saving…' : 'Submit application'}</button></form></div></div>
}
