import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { FormEvent, useState } from 'react'
import { Mail, MessageCircleQuestion } from 'lucide-react'
import { SEO } from '../components/SEO'
import { db } from '../lib/firebase'

export default function ContactPage() {
  const [message,setMessage]=useState(''); const [error,setError]=useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(''); setError(''); if (!db) { setError('Configure Firebase before sending support requests from the live form.'); return } const data=new FormData(event.currentTarget); try { await addDoc(collection(db,'supportRequests'), { name:String(data.get('name')), email:String(data.get('email')), topic:String(data.get('topic')), message:String(data.get('message')), createdAt:serverTimestamp(), status:'new' }); event.currentTarget.reset(); setMessage('Your message has been sent to WorkShake support.') } catch(e){ setError(e instanceof Error?e.message:'Could not send your message.') } }
  return <div className="page-shell"><SEO title="Contact WorkShake" description="Contact WorkShake for account, provider or platform support." path="/contact" /><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-black uppercase tracking-[.2em] text-olive">Support</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-5xl">Tell us what you need help with.</h1><p className="mt-4 text-lg leading-8 text-forest/80">Use this form for account, provider and platform questions. For an emergency involving immediate danger, contact the appropriate local emergency service instead.</p><div className="mt-7 space-y-3 text-sm text-forest/80"><p className="flex gap-2"><Mail className="h-5 w-5" /> support@workshake.example</p><p className="flex gap-2"><MessageCircleQuestion className="h-5 w-5" /> Support requests are tracked in the platform.</p></div></div><form onSubmit={submit} className="grid gap-5 rounded-[2rem] border border-forest/10 bg-mist p-6 shadow-soft"><div className="grid gap-5 sm:grid-cols-2"><label className="form-field"><span className="form-label">Name</span><input required name="name" className="form-input" /></label><label className="form-field"><span className="form-label">Email</span><input required type="email" name="email" className="form-input" /></label></div><label className="form-field"><span className="form-label">Topic</span><select name="topic" className="form-select"><option>Account help</option><option>Provider application</option><option>Booking or job</option><option>Safety concern</option><option>Other</option></select></label><label className="form-field"><span className="form-label">Message</span><textarea required minLength={20} name="message" className="form-textarea" /></label>{error&&<p className="rounded-xl bg-sun p-3 text-sm font-bold" role="alert">{error}</p>}{message&&<p className="rounded-xl bg-sage p-3 text-sm font-bold" role="status">{message}</p>}<button className="btn-primary w-fit">Send message</button></form></div></div>
}
