import { BadgeCheck, BriefcaseBusiness, Clock3, MapPin, Star } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { PlaceholderArt } from '../components/PlaceholderArt'
import { SEO } from '../components/SEO'
import { providers } from '../data/providers'

export default function ProviderDetailPage() {
  const { id } = useParams()
  const provider = providers.find((p) => p.id === id)
  if (!provider) return <div className="page-shell"><h1 className="text-4xl font-black">Provider not found</h1><Link to="/providers" className="btn-primary mt-5">Back to providers</Link></div>
  const schema = { '@context': 'https://schema.org', '@type': 'ProfessionalService', name: provider.name, description: provider.bio, areaServed: provider.location, aggregateRating: { '@type': 'AggregateRating', ratingValue: provider.rating, reviewCount: provider.reviews } }
  return <div className="page-shell"><SEO title={`${provider.name} — ${provider.category} | WorkShake`} description={provider.bio} path={`/provider/${provider.id}`} jsonLd={schema} /><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><PlaceholderArt label="Add provider profile photo" className="min-h-[28rem]" /><div><div className="flex items-center gap-3"><span className="status-pill">{provider.category}</span>{provider.verified && <span className="inline-flex items-center gap-1 text-sm font-bold text-forest"><BadgeCheck className="h-4 w-4" /> Verified</span>}</div><h1 className="mt-4 text-4xl font-black tracking-[-.05em] text-ink sm:text-5xl">{provider.name}</h1><p className="mt-4 text-lg leading-8 text-forest/80">{provider.bio}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-sage/55 p-4"><Star className="h-5 w-5 fill-sun" /><p className="mt-3 text-2xl font-black">{provider.rating}</p><p className="text-sm text-forest/70">{provider.reviews} reviews</p></div><div className="rounded-2xl bg-sage/55 p-4"><BriefcaseBusiness className="h-5 w-5" /><p className="mt-3 text-2xl font-black">{provider.jobs}</p><p className="text-sm text-forest/70">jobs completed</p></div></div><div className="mt-6 flex flex-wrap gap-4 text-sm font-bold text-forest/75"><span className="inline-flex gap-1.5"><MapPin className="h-4 w-4" />{provider.location}</span><span className="inline-flex gap-1.5"><Clock3 className="h-4 w-4" />Replies in {provider.responseTime}</span></div><div className="mt-6 flex flex-wrap gap-2">{provider.skills.map((s) => <span className="status-pill" key={s}>{s}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link to={`/messages?with=${provider.id}`} className="btn-primary">Message provider</Link><Link to={`/book/${provider.id}`} className="btn-secondary">Request booking</Link><Link to="/post-problem" className="btn-secondary">Post a matching job</Link></div></div></div><section className="mt-16"><h2 className="text-2xl font-black">About pricing</h2><p className="mt-3 max-w-2xl text-forest/80">Jobs start around <strong>${provider.startingPrice}</strong>. Final price depends on scope, parts, travel and timing. Confirm the full quote in WorkShake before the job begins.</p></section></div>
}
