import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { FormEvent, useState } from 'react'
import { Star } from 'lucide-react'
import { SEO } from '../components/SEO'
import { testimonials } from '../data/testimonials'
import { useAuth } from '../context/AuthContext'
import { db } from '../lib/firebase'

export default function ReviewsPage() {
  const { user } = useAuth(); const [message, setMessage] = useState(''); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); if (!db || !user) { setError('Sign in with Firebase configured before leaving a review.'); return } const data = new FormData(event.currentTarget); await addDoc(collection(db,'reviews'), { authorId: user.uid, authorName: user.displayName || 'WorkShake user', rating: Number(data.get('rating')), body: String(data.get('body')).trim(), createdAt: serverTimestamp() }); event.currentTarget.reset(); setMessage('Thanks. Your review was submitted.') }
  return <div className="page-shell"><SEO title="Customer reviews | WorkShake" description="Read verified WorkShake reviews and learn how ratings support trusted local work." path="/reviews" /><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-olive">Reviews</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em] sm:text-5xl">Trust grows one completed job at a time.</h1><p className="mt-4 text-lg leading-8 text-forest/80">Ratings help people understand communication, reliability and the quality of the completed work.</p></div><div className="mt-9 grid gap-5 md:grid-cols-3">{testimonials.map((item) => <blockquote key={item.name} className="card-lift rounded-[2rem] bg-sage/45 p-6"><div className="flex gap-1">{Array.from({length:5}).map((_,i) => <Star key={i} className="h-4 w-4 fill-sun text-forest" />)}</div><p className="mt-5 font-bold leading-7">“{item.quote}”</p><footer className="mt-5 text-sm text-forest/70">{item.name} · {item.role}</footer></blockquote>)}</div><form onSubmit={submit} className="mt-12 max-w-2xl rounded-[2rem] border border-forest/10 bg-mist p-6 shadow-soft"><h2 className="text-2xl font-black">Leave a WorkShake review</h2><div className="mt-5 grid gap-4"><label className="form-field"><span className="form-label">Rating</span><select className="form-select" name="rating" defaultValue="5"><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Okay</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label className="form-field"><span className="form-label">Your review</span><textarea minLength={20} maxLength={700} required className="form-textarea" name="body" /></label>{error && <p className="rounded-xl bg-sun p-3 text-sm font-bold" role="alert">{error}</p>}{message && <p className="rounded-xl bg-sage p-3 text-sm font-bold" role="status">{message}</p>}<button className="btn-primary w-fit">Submit review</button></div></form></div>
}
